### ISSUE TITLE
Access token visible in process command.

### ISSUE THREAD

**Issue by mtwilliams** [tsutsu/github-auth3#1]
Enterprising individuals can grab the access token using something like `ps`.

**Comment by tsutsu** [comment]
Yep. The workaround for this specified in the README (writing a wrapper script that reads from a secure file and passes the arg) doesn't help much, given that `/proc/$pid/cmdline` is world-readable.

The slight tweak of taking the access-token as an env-var rather than a flag would be _mostly_ secure. You could use the same wrapper-script solution, and `/proc/$pid/environ` is only owner-readable (so the superuser, or some other process started by the same user, could read off the env, but that same set of actors could also just `ptrace` the process to pry things out of its memory directly.)

The idiot-proof thing to do here, though, is to just take a flag on the command-line, which is not the token itself, but rather the path to the file the token will be read from. (It can also ensure said file's `perms & 077 == 0` while it's at it.) That's probably the solution to go with.

**Comment by mtwilliams** [comment]
+1 for reading (and sanity checking) the token from a file
